matrix:
  include:
    - language: node_js
      node_js:
        - 7
      cache:
        directories:
          - webapp/node_modules
      before_script:
        - cd webapp
      script:
        - npm install
        - npm run build
        - npm test
